{% set name = "python-json-logger" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f58e68eb46e1faed27e0f574a55a0455eecd7b8a5b88b85a784519ba3cff047f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - pythonjsonlogger
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/madzak/python-json-logger
  license_file: LICENSE
  license: BSD-2-Clause
  license_family: BSD
  summary: A python library adding a json log formatter
  description: |
    This library is provided to allow standard python logging to output log
    data as json objects. With JSON we can make our logs more readable by
    machines and we can stop writing custom parsers for syslog type records.

extra:
  recipe-maintainers:
    - sodre
    - blink1073
