{% set name = "python-json-logger" %}
{% set version = "2.0.3" %}
{% set sha256 = "387d0e0bd74df0b47b857c2d13dd2110f98a52bf0e683b2be463d23bc307f285" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - pythonjsonlogger

about:
  home: http://github.com/madzak/python-json-logger
  license_file: LICENSE
  license: BSD 2-clause
  license_family: BSD
  summary: A python library adding a json log formatter
  description: |
    This library is provided to allow standard python logging to output log
    data as json objects. With JSON we can make our logs more readable by
    machines and we can stop writing custom parsers for syslog type records.

extra:
  recipe-maintainers:
    - sodre
    - ukaratay
