{% set name = "python-json-logger" %}
{% set version = "3.2.1" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8eb0554ea17cb75b05d2848bc14fb02fbdbd9d6972120781b974380bfa162008

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - typing_extensions

test:
  imports:
    - pythonjsonlogger
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/nhairs/python-json-logger
  license_file: LICENSE
  license: BSD-2-Clause
  license_family: BSD
  summary: JSON Log Formatter for the Python Logging Package
  description: |
    This library is provided to allow standard python logging to output log
    data as json objects. With JSON we can make our logs more readable by
    machines and we can stop writing custom parsers for syslog type records.

extra:
  recipe-maintainers:
    - sodre
    - ukaratay
    - blink1073
